language: cpp
compiler:
  - gcc
  - clang
env:
  - USE_LUA=true
  - USE_LUA=false
before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
install: 
  - sudo apt-get install -y -qq autoconf automake libtool make g++ libpq-dev libxml2-dev libbz2-dev libproj0 proj-bin libproj-dev # core deps
  - sudo apt-get install -y -qq boost1.55 
  - sudo apt-get install -y -qq protobuf-c-compiler libprotobuf-c0-dev
  - sudo apt-get install -y -qq libgeos-3.3.3 libgeos-dev libgeos++-dev
  - |-
    if [ "${USE_LUA}" = "true" ]; then
      sudo apt-get install -y -qq lua5.2 liblua5.2-dev
    fi
before_script:
  - xml2-config --version
  - geos-config --version
  - proj | head -n1
  - |-
    if [ "${USE_LUA}" = "true" ]; then
      lua -v
    fi
script:
  ./autogen.sh && ./configure && make -j2
after_failure:
  - cat config.log
